kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: install-dependencies
  image: node:10.13.0-alpine
  commands:
  - npm i -g yarn
  - yarn

- name: lint
  image: node:10.13.0-alpine
  commands:
  - yarn run lint

- name: build-dist
  image: node:10.13.0-alpine
  commands:
  - yarn run prod
  when:
    ref:
    - refs/tags/*

- name: build-linux-server
  image: golang
  environment:
    GOOS: linux
    CGO_ENABLED: 0
  commands:
  - go build -o webserver server/main.go
  when:
    ref:
    - refs/tags/*

- name: dockerize
  image: plugins/docker
  settings:
    auto_tag: true
    repo: carldanley/website
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/tags/*

- name: deploy-production
  image: lachlanevenson/k8s-kubectl
  environment:
    KUBECONFIG:
      from_secret: kubeconfig
    KUBE_CONFIG: /kube.config
  commands:
  - printenv KUBECONFIG | base64 -d > /kube.config
  - cat /kube.config
  - kubectl get deployments -n carldanley-com
