kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci
  namespace: carldanley-com
subjects:
- kind: ServiceAccount
  name: ci
  namespace: carldanley-com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
